config:
  message_throttle: 1
  max_random_msg_sleep: 0
<<<<<<< HEAD
  plan_interval: -1 # -1 = deactivated
  memory_interval: -1 # -1 = deactivated
=======
  plan_interval: 180 # -1 = deactivated
  memory_interval: 30 # -1 = deactivated
>>>>>>> refs/remotes/origin/main
  model: "llama3.2"
  base-plan: ""
  channel_id: 1
  sequential_mode: True
  random_ignore: False
  impulses: False
  save_logs: False
  persitance_prefix: 'qa_bench'