config:
  message_throttle: 5
  max_random_msg_sleep: 5
  plan_interval: 5 # -1 = deactivated
  memory_interval: 5 # -1 = deactivated
  model: "llama3.2"
  base-plan: ""
  initial-channel-id: 1
  sequential_mode: True
  random_ignore: True
  impulses: False