config:
  message_throttle: 10
  max_random_msg_sleep: 60
  plan_interval: 360
  memory_interval: 60
  model: "llama3.2"
  base-plan: ""
  initial-channel-id: 1350127264871743498
  sequential_mode: False
  random_ignore: False
  impulses: False