config:
  # Routine Configuration
  # response_delay -> Guaranteed sleep @ the end of each cycle
  # max_random_response_delay -> random sleep between 0 & defined value
  response_delay: 1 # -> Guaranteed sleep @ the end of each cycle
  max_random_response_delay: 1 # -> random sleep between 0 & defined value
  sequential_mode: True # If sequential, manual channel switch & all messages are processed ASAP

  # Module toggles
  memories: True # Enable / Disable creation of memories
  plans: True # Enable / Disable creation of plans

  # Persistance
  persistance_prefix: 'qa_bench' # prefix identifying agent memories. new prefix = new memories
  persistance_path: 'output/qa_bench/memories' # path to agent memories (or where they should be stored)

  # Agent
  model: "llama3:8b" # Base model for the agent
  base_plan: "I should respond to every single message." # Plan for the agent. Will change if plans = True
  channel_id: 1 # Channel the agent is monitoring. Change dynamically if sequential_mode is off. Random if non-existant.

  # Logs
  save_logs: True # Save module outputs as pickles
  log_path: 'output/qa_bench/logs' # where module output should be saved
  log_level: 30 # log level to show from the console (only for the agent)
