config:
  # Routine Configuration
  # response_delay -> Guaranteed sleep @ the end of each cycle
  # max_random_response_delay -> random sleep between 0 & defined value
  response_delay: 0 # -> Guaranteed sleep @ the end of each cycle
  max_random_response_delay: 45 # -> random sleep between 0 & defined value
  sequential_mode: False # If sequential, manual channel switch & all messages are processed ASAP

  # Module toggles
  memories: True # Enable / Disable creation of memories
  plans: True # Enable / Disable creation of plans

  # Persistance
  persistance_prefix: 'discord_server' # prefix identifying agent memories. new prefix = new memories
  persistance_path: 'output/memories' # path to agent memories (or where they should be stored)

  # Agent
  model: "llama3:8b" # Base model for the agent
  base_plan: "I should respond to every single message." # Plan for the agent. Will change if plans = True
  channel_id: 1362178271323623697 # Channel the agent is monitoring. Will change dynamically if sequential_mode is off and >= 2 channels

  # Logs
  save_logs: False # Save module outputs as pickles
  log_path: 'output/logs' # where module output should be saved
  log_level: 40 # log level to show from the console (only for the agent)
