config:
  response_delay: 1
  max_random_response_delay: 0
  plan_interval: -1 # -1 = deactivated
  memories: True # -1 = deactivated
  model: "llama3:8b"
  base-plan: ""
  channel_id: 1
  sequential_mode: True
  random_ignore: False
  impulses: False
  save_logs: False
  persitance_prefix: 'promptbench'
  persistance_path: 'memories'
  log_path: 'logs'
