config:
  response_delay: 1
  max_random_response_delay: 1
  plan_interval: -1 # -1 = deactivated1
  memories: False # -1 = deactivated
  plans: False
  model: "llama3:8b"
  base-plan: ""
  channel_id: 1
  sequential_mode: True
  random_ignore: False
  impulses: False
  save_logs: False
  persitance_prefix: 'qa_bench'
  persistance_path: 'qa_bench/memories'
  log_path: 'qa_bench/logs'
